<?php

const
IBLOCK_IN = 78,
IBLOCK_IN_STATE = 79,
IBLOCK_OUT = 73,
IBLOCK_OUT_KASSA = 72,
IBLOCK_OUT_STATE = 74, 
/* LISTS BP & TEMPLATES */
LIST_FINANCE = 75,
LIST_FINANCE_TEMPLATE = 197,
LIST_FINANCE_LIMIT = 77,
LIST_FINANCE_LIMIT_TEMPLATE = 199,
LIST_FINANCE_IN = 80,
LIST_FINANCE_IN_TEMPLATE = 203,
/* PARAMS */
PARAM_OUT_FACT = 137,
PARAM_OUT_PLAN = 136,
PARAM_IN_FACT = 138,
PARAM_IN_PLAN = 139,
/* OTHERS */
_U = "/finance-module/",
REDACTOR_PERM_DEPT = 30,
PAGE_LIMIT = 15;